-- 1. Tabela de Perfis (User Onboarding Data)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  gender TEXT,
  age INTEGER,
  height INTEGER,
  weight DECIMAL,
  goal TEXT,
  activity_level TEXT,
  targets JSONB,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Tabela de Refeições
CREATE TABLE meals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  meal_type TEXT NOT NULL,
  original_text TEXT,
  items JSONB NOT NULL,
  date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Habilitar Row Level Security (RLS) - Segurança básica
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE meals ENABLE ROW LEVEL SECURITY;

-- 4. Criar políticas de acesso (cada utilizador só vê os seus dados)
CREATE POLICY "Utilizadores podem ver o seu próprio perfil" ON profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Utilizadores podem atualizar o seu próprio perfil" ON profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Utilizadores podem inserir o seu próprio perfil" ON profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Utilizadores podem ver as suas próprias refeições" ON meals
  FOR ALL USING (auth.uid() = user_id);
